
---
-
  name: clustersDeployment
  hosts: manager
  tasks:
          - name: Copy files
            copy: 
             src: /home/hooli/repo/compose/
             dest: /home/hooli/compose/

          - file:
              path: /home/hooli/compose/repo.sh
              mode: 0555

          - file:
              path: /home/hooli/compose/services.sh
              mode: 0555

          - file:
              path: /home/hooli/compose/ejabberd/scripts/lib/functions.sh
              mode: 0555

          - file:
              path: /home/hooli/compose/ejabberd/scripts/pre/30_join_cluster.sh
              mode: 0555

          - name: Borrar servicios
            script: /home/hooli/repo/compose/services.sh

          - name: Esperando a que el script finalice
            wait_for:
                    path: /tmp/clusterrm
                    search_regex: Completed

          - name: Montar repositorio
            script: /home/hooli/repo/compose/repo.sh


          - name: Desplegar DNS
            command: "{{item}}"
            with_items:
                    - docker-compose -f bind.yml up -d
                    - docker stack deploy --compose-file bind.yml bind
                    - docker service scale bind_bind=3
            args:
                    chdir: /home/hooli/compose/
          
          - name: Desplegar Wordpress
            command: "{{item}}"
            with_items:
                    - docker-compose -f wordpress.yml up -d
                    - docker stack deploy --compose-file wordpress.yml wordpress
                    - docker service scale wordpress_wordpress=3
            args:
                    chdir: /home/hooli/compose/
          
          - name: Desplegar Ejabberd
            command: "{{item}}"
            with_items:
                    - docker-compose build --no-cache --force-rm
                    - docker-compose up -d
                    - docker-compose push
                    - docker stack deploy --compose-file docker-compose.yml ejabberd
                    - docker service scale ejabberd_ejabberd=2
            args:
                    chdir: /home/hooli/compose/ejabberd/
          
